version: 2

project_name: dfm

before:
  hooks:
    - go mod tidy

dist: .bin

builds:
  - id: dfm
    main: .
    binary: dfm
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.revision={{.Tag}}-{{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template:  >-
     {{.ProjectName}}_
     {{- .Tag}}_
     {{- if eq .Os "darwin"}}macos
     {{- else}}{{.Os}}{{end}}_
     {{- if eq .Arch "amd64"}}x86_64
     {{- else}}{{.Arch}}{{end}}
    formats: [tar.gz]
    files:
      - README.md
      - LICENSE
      - docs/*

snapshot:
  version_template: "{{ incpatch .Version }}-next"



release:
  draft: true
  prerelease: auto
